using System.Collections;
using System.Collections.Generic;
using System;
using UnityEngine;

public class LevelUp : MonoBehaviour
{
    [SerializeField] private PlayerStatus playerStatus;
    [SerializeField] private UpgradeStatus upgradeStatus;
    [SerializeField] private StatusValueText statusValueText;

    // ฟไฑธ ฐๆว่ฤก ex) ทนบง 1 -> ทนบง 2 ฟไฑธ ฐๆว่ฤก = requiredExp[1].
    public static readonly int[] requiredExp;

    private void Update()
    {
        Debug.Log($"Level {playerStatus.Level}: {playerStatus.Exp} / {requiredExp[(int)playerStatus.Level]}");
    }

    // ฐๆว่ฤก ล๋ มคภว.
    static LevelUp()
    {
        int maxLevel = 50; // รึด๋ ทนบง.
        double coefficient = 20; // ฐ่ผ๖.
        requiredExp = new int[maxLevel + 1];

        for (int i = 1; i <= maxLevel; i++)
        {
            double exp = Math.Pow((i * 100.0 / 99), 2) * coefficient;
            requiredExp[i] = (int)Math.Round(exp);
        }
    }

    // ฐๆว่ฤก ม๕ฐก.
    public void IncreaseExp(float value)
    {
        playerStatus.Exp += value;
        if (playerStatus.Exp > requiredExp[(int)playerStatus.Level])
        {
            UpLevel();
        }
    }

    // ทนบง พ๗.
    public void UpLevel()
    {
        playerStatus.Level++;
        upgradeStatus.SkillPoint++;
        playerStatus.Damage += 1;
        playerStatus.Hp += 5;
        playerStatus.Exp -= requiredExp[(int)playerStatus.Level - 1];
        if (playerStatus.Exp > requiredExp[(int)playerStatus.Level])
        {
            UpLevel();
        }
        statusValueText.SetupValueText(upgradeStatus);
    }

    // ทนบง รสฑโศญ.
    public void ResetLevel()
    {
        upgradeStatus.ResetStat();
        playerStatus.Damage -= playerStatus.Level - 1;
        playerStatus.Hp -= (playerStatus.Level - 1) * 5;
        playerStatus.Level = 1;
        playerStatus.Exp = 0;
    }
}
